resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: TerraformInstaller@0
    displayName: Install Terraform latest
  - task: TerraformTaskV3@3
    displayName: 'Terraform : azurerm'
    inputs:
      backendServiceArm: 1d739809-e471-42a9-b99e-1005e0b21288
      backendAzureRmResourceGroupName: app-grp
      backendAzureRmStorageAccountName: appstore151694
      backendAzureRmContainerName: data
      backendAzureRmKey: terraform.tfstate
  - task: TerraformTaskV3@3
    displayName: 'Terraform : azurerm'
    inputs:
      command: validate
  - task: TerraformTaskV3@3
    displayName: 'Terraform : azurerm'
    inputs:
      command: plan
      environmentServiceNameAzureRM: 1d739809-e471-42a9-b99e-1005e0b21288
  - task: TerraformTaskV3@3
    displayName: 'Terraform : azurerm'
    inputs:
      command: apply
      commandOptions: -auto-approve
      environmentServiceNameAzureRM: 1d739809-e471-42a9-b99e-1005e0b21288
  